services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    volumes:
      - .:/app
    restart: always
    command: sh -c "npm run prisma:generate && npm run prisma:migrate && npm run start:prod"
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - postgres-network
    env_file:
      - .env
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    networks:
      - postgres-network
    env_file:
      - .env

networks:
  postgres-network:
    driver: bridge
